### ISSUE TITLE
Pathways like WP366 throw errors

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/gpml-sync-action#1]
https://github.com/wikipathways/wikipathways-database/actions/runs/4776003043/jobs/8490733040

> [     0.028] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
[     0.664] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
[     1.016] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
[     1.253] Info:  Recognized format [Namespace: prefix "" is mapped to URI "http://pathvisio.org/GPML/2013a"]
Warn:  Unknown property: TERM
Warn:  Unknown property: Ontology
Error: Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1464)
	at java.util.Collections.sort(Collections.java:143)
	at org.pathvisio.core.model.GpmlFormat2013a.createJdom(Unknown Source)
	at org.pathvisio.core.model.GpmlFormat2013a.writeToXml(Unknown Source)
	at org.pathvisio.core.model.GpmlFormat2013a.writeToXml(Unknown Source)
	at org.pathvisio.core.model.GpmlFormat.writeToXml(Unknown Source)
	at org.pathvisio.core.model.Pathway.writeToXml(Unknown Source)
	at org.wikipathways.SyncAction.main(Unknown Source)
Error: Process completed with exit code 1.

**Comment by AlexanderPico** [comment]
Please restore "approved" tag on WP366 when pathway or code is fixed.

**Comment by egonw** [comment]
[WP1045](https://classic.wikipathways.org/index.php/Pathway:WP1045) is another one. I also removed the "approved" tag on that one. It's an homology converted pathway, btw.

**Comment by egonw** [comment]
I can confirm the 2.1 version has the same problem, but it's nice that that one reports the failing pathway.

(Oh, and I think we may have in one of the other repositories another failing pathway somewhere, that may have the same course?)
